[
 {deps, [
    {jsx, ".*", {git, "git://github.com/talentdeficit/jsx.git", "c61be973b95ba4cc5fd646d1f80b65b8eeba8376"}},
    {lhttpc, ".*", {git, "git://github.com/esl/lhttpc.git", "6530ef818bf904bf4ef615f384d2fc7bae44a6dc"}}
 ]},
 {ct_dir, "test"},
 {ct_log_dir, "test/logs"},
 {cover_enabled, true},
 {erl_opts, [debug_info]},
 {xref_checks, [undefined_function_calls, undefined_functions,
               locals_not_used, deprecated_function_calls, deprecated_functions]}
].
