[
 {deps, [
    {jsx, ".*", {git, "git://github.com/talentdeficit/jsx.git", "c61be973b95ba4cc5fd646d1f80b65b8eeba8376"}},
    {lhttpc, ".*", {git, "git://github.com/theorix/lhttpc.git", "be9472ff65a2056e84449277a30acc5e67fc2ab8"}}
 ]},
 {ct_dir, "test"},
 {ct_log_dir, "test/logs"},
 {cover_enabled, true},
 {erl_opts, [debug_info]},
 {xref_checks, [undefined_function_calls, undefined_functions,
               locals_not_used, deprecated_function_calls, deprecated_functions]}
].
