[
 {deps, [
    {jsx, ".*", {git, "git://github.com/talentdeficit/jsx.git", "da0501714bc613112c03b01ebe08f904cad9e6f6"}},
    {lhttpc, ".*", {git, "git://github.com/theorix/lhttpc.git", "1b6f44164e7df9868a02cdf005bbdca076537e9b"}}
 ]},
 {ct_dir, "test"},
 {ct_log_dir, "test/logs"},
 {cover_enabled, true},
 {erl_opts, [debug_info]},
 {xref_checks, [undefined_function_calls, undefined_functions,
               locals_not_used, deprecated_function_calls, deprecated_functions]}
].
